### ISSUE TITLE
Attempting to use code fix for S818 gives error

### ISSUE THREAD

**Issue by OsirisTerje** [SonarSource/sonarlint-vs#508] opened 2015-10-10 11:26 UTC
![image](https://cloud.githubusercontent.com/assets/203432/10410934/6a14e0d4-6f52-11e5-9d00-42b8d2957c98.png)

As far as I can see this rule doesn't have any fix yet, right ?  So the error should not appear at all.

**Comment by tvsonar** [comment] 2015-10-12 06:43
We do have a code fix for this rule (https://github.com/SonarSource/sonarlint-vs/blob/master/src/SonarLint/Rules/LiteralSuffixUpperCaseCodeFixProvider.cs), and it seems that it fails on some input. Could you provide us information on what code you had in your editor when you encountered this exception?

**Comment by OsirisTerje** [comment] 2015-10-12 08:06
I noticed it on code like this:
![image](https://cloud.githubusercontent.com/assets/203432/10423617/922bdc2c-70c8-11e5-8b96-5044a67166a7.png)
And after this error, a series of the LiteralSuffixUpperCaseFixProvider error.

I also see this error coming immediately when I open the solution.  Not sure what triggers that. It then just appears again and again.

**Comment by tvsonar** [comment] 2015-10-12 08:48
Do you have other Roslyn based analyzers enabled? The `BatchFixAllProvider` comes with Roslyn, and can be reused to provide the batch fixing experience. The `LiteralSuffixUpperCaseFixProvider` also uses it, so if the `BatchFixAllProvider` fails then that might affect other code fixes as well. 

I can't reproduce this issue on our side. One way to investigate it on your side is running VS with `devenv.exe /log` and then checking the ActivityLog.xml in C:\Users\[Login]\AppData\Roaming\Microsoft\VisualStudio\14.0.

**Comment by tvsonar** [comment] 2015-10-21 08:27
@OsirisTerje could you investigate the issue further? Can you help me in reproducing this issue?

**Comment by wimr** [comment] 2015-10-28 09:30
Hi, I have the same error. The error log states the following entry: 
<entry>
    <record>802</record>
    <time>2015/10/28 09:30:19.472</time>
    <type>Error</type>
    <source>LiteralSuffixUpperCaseCodeFixProvider</source>
    <description>Unable to cast object of type &apos;Microsoft.CodeAnalysis.CSharp.Syntax.ArgumentSyntax&apos; to type &apos;Microsoft.CodeAnalysis.CSharp.Syntax.LiteralExpressionSyntax&apos;.&#x000D;&#x000A;   at SonarLint.Rules.LiteralSuffixUpperCaseCodeFixProvider.&lt;RegisterCodeFixesAsync&gt;d__4.MoveNext() in C:\SourcesTv\release\sonarlint-vs\src\SonarLint\Rules\LiteralSuffixUpperCaseCodeFixProvider.cs:line 53&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.CodeAnalysis.Extensions.IExtensionManagerExtensions.&lt;PerformActionAsync&gt;d__2.MoveNext()</description>
  </entry>

**Comment by tvsonar** [comment] 2015-10-28 09:38
@wimr Thanks for reporting this problem. It should be fixed by #515, which will be part of the 1.4.0 release.

**Comment by tvsonar** [comment] 2015-11-16 13:53
@wimr This bug was fixed in 1.4.0. If you still come across this, please report another issue.

**Closed by tvsonar** 2015-11-16 13:53 UTC
Labels: bug
