### ISSUE TITLE
S2758 Operation returns same value when true or false (False Positive)

### ISSUE THREAD

**Issue by njannink** [SonarSource/sonarlint-vs#412] opened 2015-09-15 09:40 UTC
I get a false positive on the following code:

```
return MyObject.IsSelected ? $"{Value:0.00}" : $"{Value:c}";
```

**Comment by tvsonar** [comment] 2015-09-16 14:04
@njannink Thanks for reporting this issue. I confirm that I could reproduce it. The problem comes from Roslyn itself, it is reporting the two interpolated strings to be the same. I'll investigate it a bit more and then report this issue to the Roslyn team.

**Comment by tvsonar** [comment] 2015-09-16 14:32
related to https://github.com/dotnet/roslyn/issues/5271

**Comment by njannink** [comment] 2015-09-16 16:49
Thank you

**Comment by tvsonar** [comment] 2015-12-10 09:23
@njannink This issue seems to be fixed in Roslyn 1.1. I can't reproduce it anymore on Visual Studio 2015 Update 1.

**Closed by tvsonar** 2015-12-10 09:23 UTC
Labels: false-positive
